version: "3.4"
services:

  api:
    build:
      context: .
      dockerfile: src/CleanArchitecture.Api/Dockerfile
    image: ${DOCKER_REGISTRY}cleanarchitecture/api:${TAG:-latest}
    profiles: ["server", "cd"]

  web:
    build:
      context: .
      dockerfile: src/CleanArchitecture.Web/Dockerfile
    image: ${DOCKER_REGISTRY}cleanarchitecture/web:${TAG:-latest}
    profiles: ["web", "cd"]

  migrations:
    build:
      context: .
      dockerfile: src/CleanArchitecture.Migrations/Dockerfile
    image: ${DOCKER_REGISTRY}cleanarchitecture/migrations:${TAG:-latest}
    profiles: ["server", "cd"]

  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    profiles: ["dev"]
    container_name: cleanarchitecture-sql
    platform: linux/amd64
    user: root
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - "MSSQL_SA_PASSWORD=Admin1234!"
    volumes:
      - cleanarchitecture-sql:/var/opt/mssql/data

  ui-tests:
    build:
      context: .
      dockerfile: tests/CleanArchitecture.AcceptanceTests/Dockerfile
      args:
        PAT: ${PAT}
    image: ${DOCKER_REGISTRY}cleanarchitecture/acceptancetests:${TAG:-latest}
    container_name: weather-acceptancetests${TAG:-dev}
    environment:
      - Browser__Headless=true
      - Browser__SlowMoMilliseconds=150
      - Browser__BaseUrl=${BaseUrl}
    profiles: ["ui-tests"]


volumes: # this volume ensures that data is persisted when the container is deleted
  cleanarchitecture-sql: